feat(app): agrego context para consumir planeta desde AppRouter
nsdonato/vamosacodearplanetas pull request #10
Opened 2022-09-09 03:58 UTC by phreakphreak

2022-09-09 14:49 UTC, nsdonato requested changes

2022-09-09 14:49 UTC, nsdonato commented on src/components/Layout.tsx
> +      {planet !== undefined && (
no es necesario el !== ya que se trata como un valor truthy o falshy, por ende si es undefined directamente no valida lo del lado derecho, si tiene algo muestra el componente 😊

2022-09-09 14:52 UTC, nsdonato commented on src/hooks/usePlanet.tsx
> +  if (context === undefined) {
No es necesario igualar a undefined, con negar el valor (ya que undefined es igual a false) estaría 🚀

2022-09-09 14:55 UTC, nsdonato commented on src/interfaces/index.d.ts
> +  export interface ContentPlanet {
Para separar responsabilidades, los tipos del response los separaría en otro archivo y desde el index hacer un barrel.

2022-09-09 14:56 UTC, nsdonato commented on src/routers/AppRouter.routing.tsx
> +      <PlanetProvider>
Lo pasaría a wrappear <App>, más que nada porque acá si o si lo necesitamos en toda la pap, de paso evitamos la duplicación de código por ruta.

2022-09-09 15:01 UTC, phreakphreak commented on src/hooks/usePlanet.tsx
> +  if (context === undefined) {
tuve que agregar la regla al linter, era mas por eso 😅

2022-09-09 15:02 UTC, phreakphreak commented on src/components/Layout.tsx
> +      {planet !== undefined && (
igualmente la misma regla aplicaba aqui, pero ya quedo 🙃

2022-09-09 15:40 UTC, phreakphreak commented on src/interfaces/index.d.ts
> +  export interface ContentPlanet {
he creado un archivo planet.d.ts
![image](https://user-images.githubusercontent.com/91038818/189388463-beb53ff5-f595-49b3-a7ae-e6c0214aeb85.png)

En el barrel con los definicion types bastaria solo con nombrar igual que el modulo "PlanetTypes"
![image](https://user-images.githubusercontent.com/91038818/189388623-4796c0e3-fea4-4bf5-b3b7-550a451db0d3.png)

segun lo que veo esto se encarga de mapear todos los tipos que tengan ese modulo
![image](https://user-images.githubusercontent.com/91038818/189388888-53524db6-a74c-41fd-b9ec-c79068fa9398.png)

2022-09-09 15:41 UTC, phreakphreak commented on src/interfaces/index.d.ts
> +  export interface ContentPlanet {
entonce el archivo index quedaria asi 
![image](https://user-images.githubusercontent.com/91038818/189389100-51b21f0d-a5df-4311-8945-9fc78090dda5.png)

2022-09-09 15:46 UTC, phreakphreak commented on src/routers/AppRouter.routing.tsx
> +      <PlanetProvider>
🤔 aqui si se wrappea toda la app se tendria que hacer fetch de todos los planetas?

2022-09-09 15:54 UTC, nsdonato commented on src/routers/AppRouter.routing.tsx
> +      <PlanetProvider>
O sea, si, pero se estaría haciendo dos veces, una por ruta linea 11 y 13 linea 17 y 19. En cambio podes pasar este Provider a App.tsx y es más, viendo el código, hasta me parece (a mi ), demás el archivo AppRouter, pero lo podemos debatir. Se entiende?

2022-09-09 15:56 UTC, nsdonato commented on src/interfaces/index.d.ts
> +  export interface ContentPlanet {
yo lo de la ClassProps lo dejaría aparte porque no tiene que ver con los planetas, sino con los componentes, que decís?

2022-09-09 17:41 UTC, phreakphreak commented on src/interfaces/index.d.ts
> +  export interface ContentPlanet {
Si lo estructuramos como si fueran modulos de un paquete? 🤔

![image](https://user-images.githubusercontent.com/91038818/189411665-8b23704e-f308-4dbf-9b45-0abff5f6f9be.png)

Ejemplo: 
- para lo components nose poner algo tipo @planet/components 
- para los types de response tener algo como @planet/types

2022-09-09 17:44 UTC, nsdonato commented on src/interfaces/index.d.ts
> +  export interface ContentPlanet {
Me gusta eh, buena propuesta!!

2022-09-12 22:51 UTC, nsdonato approved these changes
Aprobado

2022-09-12 22:52 UTC, ezequielmagi approved these changes

2022-09-12 22:52 UTC, gonzarrod approved these changes
Aprobado :)

2022-09-12 22:52 UTC, MartinIglesias86 reviewed
Approved

2022-09-12 22:53 UTC, merged

2022-09-12 22:53 UTC, ivanlolivier commented on src/context/PlanetContext.tsx
> +  planet: Planet | undefined;
nit: 
```suggestion
  planet?: Planet;
```