feat(navbar): ahora se puede ver cual planeta esta seleccionado en el navbar
nsdonato/vamosacodearplanetas pull request #13
Opened 2022-09-17 00:51 UTC by Davidr2998

Ahora los conjuntos de botones del navbar cuentan con un elemento visual que permite al usuario entender que planeta esta seleccionado.

Adjunto visual:
![Screen Shot 2022-09-16 at 19 51 20](https://user-images.githubusercontent.com/30534965/190834038-5b55c6bc-320e-470d-8754-6c4783d6c2bc.png)

2022-09-17 01:06 UTC, ivanlolivier approved these changes
Esta super bien.. comento algunos detalles

2022-09-17 01:06 UTC, ivanlolivier commented on src/components/Layout.tsx
> +        </>
Porque este cambio? creo que no es necesario

2022-09-17 01:06 UTC, ivanlolivier commented on src/components/MenuPlanets.tsx
> +  selectedPlanet: string | undefined;
```suggestion
  selectedPlanet?: string;
```

2022-09-17 01:06 UTC, ivanlolivier commented on src/components/NavHeader.tsx
> +  selectedPlanet: string | undefined;
```suggestion
  selectedPlanet?: string;
```

2022-09-17 01:06 UTC, ivanlolivier commented on src/routers/AppRouter.routing.tsx
> +  // eslint-disable-next-line @typescript-eslint/no-unused-vars
es este comentario necesario? tenía entendido que si la variable empezaba con `_` ts no lo marcaba como error (capaz es una configuración)

2022-09-17 01:06 UTC, ivanlolivier commented on src/components/NavHeader.tsx
> +        {planets.map((p: MenuPlanetItem) => {
el `:MenuPlanetItem` no sería necesario

2022-09-17 01:19 UTC, Davidr2998 commented on src/components/Layout.tsx
> +        </>
Hola @ivanlolivier, estaba probando antes de esto un componente que habia creado y se me habia ido, por lo tanto tuve que borrarlo y dejar el componente como estaba antes.

2022-09-17 01:20 UTC, Davidr2998 commented on src/routers/AppRouter.routing.tsx
> +  // eslint-disable-next-line @typescript-eslint/no-unused-vars
Me lo marcaba como error

2022-09-17 01:47 UTC, Davidr2998 commented on src/components/NavHeader.tsx
> +  selectedPlanet: string | undefined;
Listo, cambio realizado.

2022-09-17 01:47 UTC, tmchein commented on src/components/MenuPlanets.tsx
> +  selectedPlanet: string | undefined;
Cambio realizado.

2022-09-17 03:27 UTC, phreakphreak commented on src/components/NavHeader.tsx
> +                    ? "border-t-4 border-orange-dark"
aqui los colores de cada navItem se definen dependiendo a cada planeta, podes verlo de pasarlo como props, pero seria un caso para verlo 🤔 ya que tailwind como tal no funciona de manera dinamica en respecto a las utility class

2022-09-17 03:30 UTC, Davidr2998 commented on src/components/NavHeader.tsx
> +                    ? "border-t-4 border-orange-dark"
Voy a darle una revisada manana, mientras el color este definido en el tailwind.config creeria que no debe haber ningun problema, igual no tenia conocimiento de esto, no lo habia leido en el ticket haha

2022-09-17 03:34 UTC, phreakphreak commented on src/components/NavHeader.tsx
> +  return (
la prop selectedPlanet esta pasando por dos componentes arriba se podria evitar el prop dilling recuperando el nombre del planeta usando aqui el hook usePlanet que obtiene la informacion del planeta actual desde el provider

2022-09-17 03:37 UTC, Davidr2998 commented on src/components/NavHeader.tsx
> +  return (
El problema de eso es que el navheader no esta utilizando la informacion del planet provider, por lo cual no podria hacer uso de el usePlanet, por eso en el Layout saqué el param para saber el planeta seleccionado

2022-09-17 04:34 UTC, phreakphreak requested changes
Ahora podrias ver el comentario del  [NavHeader](https://github.com/nsdonato/vamosacodearplanetas/pull/13/files/88e43d41dd5de38c4ca671ba72883f2174645441#r973533516) sin preocuparte del prop dilling 🙂

2022-09-17 04:34 UTC, phreakphreak commented on src/components/NavHeader.tsx
> +  return (
la prop selectedPlanet esta pasando por dos componentes arriba se podria evitar el prop dilling recuperando el nombre del planeta usando aqui el hook usePlanet que obtiene la informacion del planeta actual desde el provider

2022-09-17 04:54 UTC, Davidr2998 commented
@ivanlolivier @phreakphreak Voy a cerrar este PR porque ya la solución que implementé quedó plasmada en el siguiente [Pull request](https://github.com/nsdonato/vamosacodearplanetas/pull/14)

2022-09-17 05:35 UTC, ivanlolivier commented
> @ivanlolivier @phreakphreak Voy a cerrar este PR porque ya la solución que implementé quedó plasmada en el siguiente [Pull request](https://github.com/nsdonato/vamosacodearplanetas/pull/14)

👍 buen trabajo!

2022-09-17 16:29 UTC, phreakphreak commented
@Davidr2998 este [PR](https://github.com/nsdonato/vamosacodearplanetas/pull/14) esta mergeado en esta rama, y los cambios que realizes se fusionaran en la rama principal, creo que no se deberia cerrar aun 🤔

2022-09-17 18:24 UTC, phreakphreak approved these changes

2022-09-17 20:03 UTC, ivanlolivier approved these changes
Solo un comentario chiquito

2022-09-17 20:03 UTC, ivanlolivier commented on src/components/NavHeader.tsx
> +}
No usamos más `selectedPlanet` como una prop del `NavHeader`

2022-09-17 20:38 UTC, Davidr2998 commented on src/components/NavHeader.tsx
> +}
Resuelto en el ultimo commit, gracias por los comentarios <3

2022-09-18 04:34 UTC, ivanlolivier approved these changes

2022-09-19 16:53 UTC, nsdonato commented
Si bien se puede ver el planeta seleccionado, el color no es el correcto para cada planeta (ver figma de ser posible), gracias!

2022-09-19 18:04 UTC, nsdonato requested changes
Si bien se puede ver el planeta seleccionado, el color no es el correcto para cada planeta (ver figma de ser posible), gracias!

2022-09-20 04:07 UTC, Davidr2998 commented
@nsdonato Los cambios fueron realizados, por favor revisar el video en la decripcion del PR

2022-09-20 04:46 UTC, phreakphreak approved these changes

2022-09-20 15:01 UTC, nsdonato requested changes

2022-09-20 15:01 UTC, nsdonato commented on src/components/NavHeader.tsx
> +  mercury: "border-teal",
Se puede hacer algo para poder respetar los colores de figma?

 blue: "#2D68F0", -> neptune
      teal: "#419EBB", -> mercury
      "orange-light": "#EDA249", -> venus
      violet: "#6D2ED5", -> earth
      "red-light": "#D14C32", -> mars
      red: "#D83A34", -> jupiter
      "orange-dark": "#CD5120", -> saturn
      "green-light": "#1EC1A2", -> uranus

2022-09-20 16:05 UTC, nujovich commented on src/components/NavHeader.tsx
> +  mercury: "border-teal",
Sí, se puede configurar en la parte del archivo de tailwind donde dice theme: extend{}. Yo puedo contribuir con eso si quieren

2022-09-20 19:46 UTC, nsdonato approved these changes

2022-09-20 20:33 UTC, phreakphreak commented
@Davidr2998 podes mergear tu rama, ya tienes dos aproves 🙂

2022-09-20 22:09 UTC, merged