Feature/planet info
nsdonato/vamosacodearplanetas pull request #20
Opened 2022-09-29 20:56 UTC by nujovich

# Vamoacodearplanetas Pull Request 🪐

## Descripcion ✏️
Agregado del componente PlanteInfo

## Cambios visuales 🎨
![image](https://user-images.githubusercontent.com/48018975/193140198-3f978d2b-7bdc-4fb5-ac0d-f23f4d18fe0b.png)

## Como testear? 🐛
Al hacer click en cada planeta, el componente debería mostrar un título, párrafo y source con link a Wikipedia

2022-09-30 18:49 UTC, nsdonato requested changes

2022-09-30 18:49 UTC, nsdonato commented on src/components/PlanetMain.tsx
> +        {/* <PlanetCardInfo /> */}
Esto quedó comentado por algo? 👀

2022-09-30 18:49 UTC, nsdonato commented on src/components/PlanetImage.tsx
> +      <img src={img} alt={imgAlt} />
Esto es de hincha, pero podremos cambiar img por src/path/url ?

2022-09-30 20:39 UTC, phreakphreak commented on src/components/PlanetMain.tsx
>      <>
aqui los fragments se pueden omitir

2022-09-30 21:12 UTC, nujovich commented on src/components/PlanetMain.tsx
> +        {/* <PlanetCardInfo /> */}
Uy, sí, me olvidé de comentarlo en el chat, me salía esto: cómo lo arreglo???
![image](https://user-images.githubusercontent.com/48018975/193356927-510d7545-e92d-493a-b88c-49e181bea7cf.png)

2022-09-30 22:07 UTC, nujovich commented on src/components/PlanetMain.tsx
> +        {/* <PlanetCardInfo /> */}
Se resolvió con el merge con main!

2022-09-30 22:34 UTC, nujovich commented on src/components/PlanetImage.tsx
> +      <img src={img} alt={imgAlt} />
Esto no lo entiendo Noe, como sería ??

2022-09-30 22:38 UTC, nsdonato commented on src/components/PlanetImage.tsx
> +      <img src={img} alt={imgAlt} />
Digo de que la prop en vez de img se llame alguna de esas opciones, me expliqué mal, perdón.

2022-09-30 22:39 UTC, ivanlolivier commented on src/components/PlanetInfo.tsx
> +    <section className="flex flex-col gap-6 w-[350px] h-[326px]">
En mi opinión, es raro definir los tamaños así tan fijos.. esta bien esto? definir el `height: 326px` ??

2022-09-30 23:08 UTC, nujovich commented on src/components/PlanetInfo.tsx
> +    <section className="flex flex-col gap-6 w-[350px] h-[326px]">
Lo saco!! traté de respetar el Figma

2022-10-08 16:34 UTC, phreakphreak approved these changes

2022-10-08 16:49 UTC, nsdonato approved these changes

2022-10-08 17:17 UTC, phreakphreak commented on src/components/PlanetMain.tsx
> +        <PlanetImage img={"img"} imgAlt={"imgAlt"} />
Tenemos un componente image en components/Image se podria reutilizar aqui?  🤔

2022-10-09 17:58 UTC, ccastillob commented on src/components/PlanetMain.tsx
> +        <PlanetImage img={"img"} imgAlt={"imgAlt"} />
A mi parecer este componente quedaría tal cual, ya que podría contener algo más complejo que solo un elemento img.

2022-10-09 22:53 UTC, phreakphreak commented
@nujovich podes realizar tu merge 🙂

2022-10-09 23:18 UTC, merged