Refactor/reducer
nsdonato/vamosacodearplanetas pull request #22
Opened 2022-10-07 04:13 UTC by phreakphreak

# Vamoacodearplanetas Pull Request 🪐

## Descripcion ✏️
Actualizo reducer y agrego types para context, se incluyeron los **commits** y **cambios pendientes** de este [PR](https://github.com/nsdonato/vamosacodearplanetas/pull/19) 

## Cambios visuales 🎨

Sin cambios visuales

## Como testear? 🐛

Sin tests para este PR

2022-10-07 21:22 UTC, nsdonato requested changes

2022-10-07 21:22 UTC, nsdonato commented on src/context/PlanetProvider.tsx
> +          type: PlanetActions.LOAD_PLANET_SUCCESS,
Para qué estarían los tipos success y demás? tenemos un loader? (en el diseño no hay)

2022-10-07 21:22 UTC, nsdonato commented on src/reducer/PlanetReducer.tsx
> +handlers[PlanetActions.LOAD_PLANET] = handleLoadPlanet;
Todo esto dependiendo la otra pregunta, nos lo podemos ahorrrar usando redux thunk

2022-10-08 16:43 UTC, phreakphreak commented on src/reducer/PlanetReducer.tsx
> +handlers[PlanetActions.LOAD_PLANET] = handleLoadPlanet;
estamos con Context API, se podria usar redux thunk 🤔?

2022-10-08 16:44 UTC, nsdonato commented on src/reducer/PlanetReducer.tsx
> +handlers[PlanetActions.LOAD_PLANET] = handleLoadPlanet;
😅 es verdad, proceda

2022-10-08 16:47 UTC, phreakphreak commented on src/context/PlanetProvider.tsx
> +          type: PlanetActions.LOAD_PLANET_SUCCESS,
el tipo success es le que recibe el planeta y lo guarda en el state del provider, el que podria estar demas seria el tipo Load

2022-10-08 16:49 UTC, nsdonato approved these changes

2022-10-11 02:22 UTC, ccastillob approved these changes

2022-10-13 23:56 UTC, merged