Refactor/Config-Tailwind
nsdonato/vamosacodearplanetas pull request #23
Opened 2022-10-07 19:16 UTC by ccastillob

# Vamoacodearplanetas Pull Request 🪐

## Descripcion ✏️
Se añade las configuraciones en Tailwind que hacían falta (colores, tamaños)

## Cambios visuales 🎨
Sin cambios visuales

## Como testear? 🐛
No se requiere

2022-10-07 21:19 UTC, nsdonato requested changes

2022-10-07 21:19 UTC, nsdonato commented on tailwind.config.cjs
> +      0.9: "-0.9px",
Buscar el resumen (pdf) en el canal, porque hay algunas medidas que no se usan. Intentamos seguir los valore de Figma para cumplir con el diseño

2022-10-07 21:19 UTC, nsdonato commented on src/index.css
> +    font-size: 16px
Si forzamos esto estamos obligando a que la fuente sea 16px (que de por si es el valor por defecto del navegador) pero si el usuario tiene otro se lo estaríamos pisando, entiendo que deberíamos.

2022-10-07 21:19 UTC, nsdonato commented on tailwind.config.cjs
> +      darkGray: "#D9D9D9",
entiendo el porqué, pero los nombres no hacen alusión a un color, es raro, pero lo podemos debatir.

2022-10-07 21:19 UTC, nsdonato commented on tailwind.config.cjs
> -        0.5: "2px",
Si sacamos esto no rompemos algo que lo esté usando?

2022-10-07 21:19 UTC, nsdonato commented on tailwind.config.cjs
> +      regular: 400,
le pusimos normal porque así estaba en. el ds pero no hay problema lo podemos dejar así. verificar no romper lo que ya lo usaba

2022-10-07 22:17 UTC, ccastillob commented on tailwind.config.cjs
> +      0.9: "-0.9px",
Lo he revisado y he puesto las medidas que se encuentran en el resumen, las cuales se utilizarían para el proyecto.
PD: Soy el que hizo el resumen 😅

2022-10-07 22:17 UTC, ccastillob commented on src/index.css
> +    font-size: 16px
Es correcto, mi navegador me jugó una mala pasada(colocaba como valor base 20px), hice la prueba en otro navegador y si era 16px. Esto lo eliminaré.

2022-10-07 22:17 UTC, ccastillob commented on tailwind.config.cjs
> +      darkGray: "#D9D9D9",
Le asigné los nombres de los planetas, ya que así sería más fácil obtener el borde (en el navbar) y background (en los botones y tabs) pasando solo border-{nombre_planeta} o bg-{nombre_planeta}.

2022-10-07 22:17 UTC, ccastillob commented on tailwind.config.cjs
> -        0.5: "2px",
Solo se estaría usando en el componente <Line />, sin embargo según el figma el height de la línea debería ser de 1px, por tanto se reemplazaría **h-0.5** por **h-px**, y no haría falta esta parte en la configuración de tailwind.

2022-10-07 22:18 UTC, ccastillob commented on tailwind.config.cjs
> +      regular: 400,
Verifiqué y no rompe nada, de hecho aún no se ha utilizado **font-normal**, también lo hice porque así figura el resumen y a mi parecer se podría tomar como guía cuando se use **font-regular**.

2022-10-08 23:43 UTC, nsdonato approved these changes

2022-10-14 00:28 UTC, phreakphreak approved these changes

2022-10-14 01:02 UTC, merged