Buttons / Tabs
nsdonato/vamosacodearplanetas pull request #25
Opened 2022-10-16 03:20 UTC by ccastillob

# Vamoacodearplanetas Pull Request 🪐

## Descripcion ✏️

Creación de los botones (Web/Tablet) y tabs (Mobile).
## Cambios visuales 🎨

**Buttons (Web/ Tablet)**
![image](https://user-images.githubusercontent.com/79947673/196016154-8fa6b3d5-8ff3-452e-8cba-c709c1c842c5.png)

**Tabs (Mobile)**
![image](https://user-images.githubusercontent.com/79947673/196016161-a230ee1b-ab05-4312-8cd7-9bca31e99d59.png)

## Como testear? 🐛

Debe de cambiar la descripción y el link de wikipedia al hacer click en una de las caracteristicas:

- Overview
- Internal Structure
- Surface Geology

2022-10-25 22:58 UTC, nsdonato requested changes

2022-10-25 22:58 UTC, nsdonato commented on src/App.tsx
> +      window.location.href = "/planets/jupiter/overview";
Por algún motivo dejamos de u sar setLocation("/planets/jupiter"); ?

2022-10-25 22:58 UTC, nsdonato commented on src/components/PlanetMain.tsx
> +    <>
Este fragment creo que está demás, porque el section hace de padre. no?

2022-10-25 22:58 UTC, nsdonato commented on src/helpers/validPathCharacteristic.ts
> +    return Object.values(listCharacteristics).includes(
podrías hacer un ternario return path ? Object.. : true

2022-10-25 22:58 UTC, nsdonato commented on src/routers/AppRouter.routing.tsx
>      </>
Creo que el fragment está demás

2022-10-26 03:00 UTC, ccastillob commented on src/App.tsx
> +      window.location.href = "/planets/jupiter/overview";
Tuve 2 motivos para dejar de usar el setLocation.
1. Al realizar una prueba como usuario que digita una URL que no es válida ejemplo: **/planets/earth/overviewasdasd**.
La URL se visualiza como /planets/jupiter/overview (lo cual está bien), sin embargo visualmente sigue mostrándose los datos del planeta tierra(en este caso la ruta anterior), lo cual a mi parecer podría generar una confusión al momento de realizar las pruebas.

![image](https://user-images.githubusercontent.com/79947673/197922579-69164fc7-674c-4301-9aeb-706bf88c2503.png)


2. Quise ahorrar la importación de wouter - useLocation, usando window.location.href, ya que de igual forma se va volver a renderizar el componente y aseguraba que visualmente se encuentre en /planets/jupiter/overview mostrando los datos del planeta Jupiter.


Para el punto #1 el código que utilicé fue el siguiente:
```
const [match, params] = useRoute("/planets/:planetName/:characteristicName");
const [, setLocation] = useLocation();

  useEffect(() => {
    if (!match || !isValidPathCharacteristic(params)) {
      setLocation("/planets/jupiter/overview", {replace: true});
    }
  }, []);
```

En este caso lo debería cambiar(utilizando el setLocation) o lo dejaría así con el **window.location.href**?

2022-10-26 03:00 UTC, ccastillob commented on src/components/PlanetMain.tsx
> +    <>
El componente PlanetCardInfo contenía un section y para evitar colocar un section(padre) dentro de otro section(PlanetCardInfo) lo coloque debajo, sin embargo ya hice las modificaciones de tal forma que sea un section padre.

2022-10-26 03:00 UTC, ccastillob commented on src/helpers/validPathCharacteristic.ts
> +    return Object.values(listCharacteristics).includes(
Cierto, ya hice la corrección. 😀

2022-10-26 03:00 UTC, ccastillob commented on src/routers/AppRouter.routing.tsx
>      </>
Se me pasó ese detalle 😅, se hizo la corrección.

2022-11-01 14:35 UTC, nsdonato approved these changes

2022-11-13 15:22 UTC, phreakphreak approved these changes

2022-11-13 15:35 UTC, merged