Feature/wouter init
nsdonato/vamosacodearplanetas pull request #5
Opened 2022-08-20 21:10 UTC by ivanFlor3s

2022-08-20 21:23 UTC, nsdonato requested changes
Deje unos comentarios

2022-08-20 21:23 UTC, nsdonato commented on package.json
> +    "husky": "^8.0.1",
Sacar el ^

2022-08-20 21:23 UTC, nsdonato commented on src/components/MenuPlanets.tsx
> +      <ul>
No es necesario un fragment porque el ul hace de padre

2022-08-20 21:23 UTC, nsdonato commented on src/components/PlanetsApp.tsx
> +    <>
No es necesario el fragment, solamente cuando hay mas de dos componentes y no queremos tener un div que los contenga innecesariamente porque no aporta a la estrcutura html.

2022-08-20 21:23 UTC, nsdonato commented on src/helpers/angular-title-pipe.ts
> +    let firstChar = stringVictima[0]
O hacemos todo en español o hacemos todo en Ingles, podemos debatirlo.

2022-08-20 21:23 UTC, nsdonato commented on src/index.css
> +ul {
Vamos a usar Tailwind 👀

2022-08-20 21:23 UTC, nsdonato commented on src/routers/AppRouter.routing.tsx
> +    <MenuPlanets></MenuPlanets>
Si el Componente no tiene childrens, se puede omitir la etiqueta de cierre de esta manera: <MenuPlanets />

2022-08-20 21:23 UTC, nsdonato commented on src/routers/AppRouter.routing.tsx
> +      <h1>Hola estas en Mercurio bienvenido</h1>
Estos h1, son necesarios? o quieren indicar que ahí iría cada componente que corresponde?

2022-08-20 21:23 UTC, nsdonato commented on src/routers/AppRouter.routing.tsx
> +  <>
Porque a este archivo parece que le faltara formatear? Creo que en este caso el fragment estaría ok, pero al no tener bien el formato no estoy segura, podrás chequear? ♥️

2022-08-20 21:30 UTC, ivanFlor3s commented on package.json
> +    "husky": "^8.0.1",
Ready, si por defecto me dejo el ^ cuando lo actualice con npm i

2022-08-20 21:31 UTC, ivanFlor3s commented on src/components/MenuPlanets.tsx
> +      <ul>
Cierto es

2022-08-20 21:33 UTC, ivanFlor3s commented on src/components/PlanetsApp.tsx
> +    <>
Lo dejaria asi, hace bastante tiempo use un curso de react y entiendo que en este archivo deberiamos agregar el context para que lo tomen todos los componentes

2022-08-20 21:33 UTC, ivanFlor3s commented on src/helpers/angular-title-pipe.ts
> +    let firstChar = stringVictima[0]
o espanglish (?
Yo lo haria todo en ingles

2022-08-20 21:34 UTC, ivanFlor3s commented on src/index.css
> +ul {
mmm... nunca use talwind, es solo un estilo para dejar esta especie de Navbar casero horizontal

2022-08-20 21:34 UTC, ivanFlor3s commented on src/routers/AppRouter.routing.tsx
> +    <MenuPlanets></MenuPlanets>
si es verdad, me dio pereza y lo deje como me lo tiro emmet

2022-08-20 21:36 UTC, ivanFlor3s commented on src/routers/AppRouter.routing.tsx
> +      <h1>Hola estas en Mercurio bienvenido</h1>
Si ahi deberia ir el componente de mercurio, por ahi estaria bueno hacer un componente que le pasemos los parametros de un planeta y resuelva que mostrar, donde y como

2022-08-20 21:38 UTC, ivanFlor3s commented on src/routers/AppRouter.routing.tsx
> +  <>
puede ser, ahi pruebo

2022-08-20 22:11 UTC, nsdonato approved these changes
Comentarios pero a modo informativo (?, aprobado.

2022-08-20 22:11 UTC, nsdonato commented on src/components/PlanetsApp.tsx
> +    <>
Es sobre main.tsx eso 😬 pero no pasa nada, después lo sacamos.

2022-08-20 22:11 UTC, nsdonato commented on src/routers/AppRouter.routing.tsx
> +      <h1>Hola estas en Mercurio bienvenido</h1>
Oki, igual la tarea en si esta hecha, era agregar wouter y nada mas. Será en otra (habría que ver si esta o falta crearla.

2022-08-20 22:13 UTC, lovera00 approved these changes
Se usara talwind...

2022-08-21 03:46 UTC, phreakphreak approved these changes

2022-08-21 03:46 UTC, phreakphreak commented on src/helpers/angular-title-pipe.ts
> +// En honor al pipe del mejor js framework
tailwind tiene un clase llamada capitalize que cambia el texto sin necesidad de js
[text transrform tailwind CSS](https://tailwindcss.com/docs/text-transform#transforming-text)

2022-08-21 17:21 UTC, merged