chore: readme explicativo
nsdonato/vamosacodearplanetas pull request #8
Opened 2022-09-05 00:30 UTC by ahernandezwitSound

nuevo readme

2022-09-05 00:41 UTC, nsdonato requested changes

2022-09-05 00:41 UTC, nsdonato commented on README.md
> +Si tienes cualquier duda puedes preguntar en nuestro [Discord](https://discord.gg/nwGE46hycg)
Podés cambiarlo por https://discord.io/vamoacodear 😊 (no se si el link ese expira)

2022-09-05 12:56 UTC, ahernandezwitSound commented on README.md
> +Si tienes cualquier duda puedes preguntar en nuestro [Discord](https://discord.gg/nwGE46hycg)
claro!

2022-09-05 12:56 UTC, ahernandezwitSound commented on README.md
> +Si tienes cualquier duda puedes preguntar en nuestro [Discord](https://discord.gg/nwGE46hycg)
Aunque me hice una inv que no expirara, no sé si te vale así.

2022-09-05 13:38 UTC, nsdonato commented on README.md
> +Si tienes cualquier duda puedes preguntar en nuestro [Discord](https://discord.gg/nwGE46hycg)
Si es posible el cambio mejor, gracias!

2022-09-05 14:48 UTC, ahernandezwitSound commented on README.md
> +Si tienes cualquier duda puedes preguntar en nuestro [Discord](https://discord.gg/nwGE46hycg)
hecho! gracias a ti!

2022-09-05 14:49 UTC, nsdonato approved these changes

2022-09-06 23:28 UTC, nsdonato requested changes

2022-09-06 23:28 UTC, nsdonato commented on README.md
> +
Podrás agregar estas extensiones al redme porfi? Gracias!
- [Tailwind CSS Intellisense](https://marketplace.visualstudio.com/items?itemName=bradlc.vscode-tailwindcss)
- [Prettier - Code formatter](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode)
- [ESLint](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint)

2022-09-06 23:29 UTC, nsdonato approved these changes

2022-09-06 23:31 UTC, phreakphreak approved these changes

2022-09-08 12:43 UTC, merged